### PR TITLE
Socket connection retry logic

### PR DESCRIPTION
**Pull request by abhishekjain88**
The change takes care of the following : 

Earlier:
When the socket gets disconnected due to any network glitch or any of the 2 services (graphite or the service sending metrics) going down temporarily, it never used to try connecting again unless the service sending the metrics was restarted. This could be really expensive as due to a small network glitch, the service needed to be restarted.

Fix:

Two new configurable parameters introduced (README.md) changed to configure the interval at which the socket connection needs to be retried and the number of times it needs to be retried.

The socket connection is retried in case of a write failure/SocketConnectException.

Please review the changes and let me know in case of any suggestions/comments.

### CODE REVIEW

**Comment by posix4e** [comment]
I made a couple of small suggestions. Overall it looks like an improvement.

**Comment by abhishekjain88** [comment]
I have fixed the code as per your suggestions. Let me know if it is good to be accepted now.

**Comment by abhishekjain88** [comment]
Hey Alex, Can you merge the code now?

**Comment by posix4e** [comment]
Sure before I merge, can you tell me how you have tested this patch set?

**Comment by abhishekjain88** [comment]
I did the following steps for testing this:
Setup : The graphite server was hosted on a machine for which I needed internet to connect to from my local box. The hadoop(namenode, datanode, jobtracker, tasktracker) services sending metrics was running on my box.

Testing scenarios:
*\* Service started after graphite server was already started while the local box being able to access the graphite server host. Verified that the connection to the graphite server was successfully established and metrics were being sent to graphite and displayed properly.
*\* Hadoop services started with graphite server down (no internet connection). Hadoop services started successfully but connection to graphite could not be established at load time. From the logs, it could be seen that a socket exception was thrown and it was being thrown again after the default retry interval of 60s. No metrics were seen on graphite. Then the graphite server was brought back up without restarting Hadoop services (internet connection restored). The connection got established in the next retry with no more SocketExceptions and the metrics could be seen on the graphite dashboard.
*\* Hadoop services started after starting graphite. So, initially the connection was established and metrics were being sent properly. Then, midway the graphite server was brought down where SocketExceptions were seen in the error logs of hadoop services and metrics stopped being sent to graphite. Graphite was then brought back up and sending of metrics restored in the next retry.

All the above were tested with and without specifying the configuration (as mentioned in the README) for the retry interval and the number of retries (so that default values were being taken in case they were not specified).

Let me know if you think I missed any of the test scenario that comes to your mind.

**Comment by posix4e** [comment]
lgtm

**Pull request merged**
